services:
  - type: web
    name: login-page-api
    env: node
    build:
      context: .
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: ~20
    domains:
      - login-page-api.onrender.com